### ISSUE TITLE
Questionnaire summary: Results from multiple choice questions

### ISSUE THREAD

**Issue by harisood** [sa-tre/satre-team#17]
### Summary of issue

Once the process for handling MCQs is decided (#11), we need to write reproducible code that allows us to get all the outputs from MCQs that can be used to open issues for the specification repo

```
    - 3) Admin control over data movement
    - 4) User authentication
    - 5) Network connectivity
    - 6. Ability to forbid copy and paste
    - 7. User experience
    - 8. Programming language support
    - 9. Enable users to install packages from selected external repositories (e.g. PyPI, CRAN, Conda, Maven)
    - 10. Commercially licenced software
    - 11. Containerisation
    - 12. Logging
    - 13. Automatic updates
    - 14. Compliance checking
    - 15. Automatic backup
    - 16. Customisable compute resources
    - 17. Additional compute beyond workspaces
    - 18. Collaborative/shared tools
    - 19. Limiting direct access to data/code
    - 20. Reproducible deployments
    - 23. Sensitivity tiering
    - 24. Which aspects of governance would it be important or useful to standardise
```

### What needs to be done?

- [x] Decide process (#11)
- [x] Write a function that can reproducibly be applied generally across MCQs to get results
- [x] Open issues for each category of question on the [specification repo](https://github.com/sa-tre/satre-specification/issues)

### Who can help?

@edwardchalstrey1 @harisood 

### Issue checklist

- [X] I have assigned the appropriate work package label to this issue, and added any other relevant labels
- [X] I have added this to the `SATRE backlog (public)` project board
- [X] I have assigned this issue to at least one person on the SATRE team

**Comment by harisood** [comment]
@edwardchalstrey1 updated list above of all multiple choice questions. I think there should be an issue for each one, with their different aspects discussed in one place.

E.g. One issue for 'admin control over data movement', that then covers results from the three questions within in (ingress, egress, streaming ingress)

We also need to think how to incorporate results from related free text questions in #18 - e.g. the MCQ for how important programming language support is, and the free text laying out the languages a TRE should support

**Comment by edwardchalstrey1** [comment]
# MCQ issues:

- https://github.com/sa-tre/satre-specification/issues/50
- https://github.com/sa-tre/satre-specification/issues/51
- https://github.com/sa-tre/satre-specification/issues/52
- https://github.com/sa-tre/satre-specification/issues/53
- https://github.com/sa-tre/satre-specification/issues/54
- https://github.com/sa-tre/satre-specification/issues/55
- https://github.com/sa-tre/satre-specification/issues/56
- https://github.com/sa-tre/satre-specification/issues/57
- https://github.com/sa-tre/satre-specification/issues/58
- https://github.com/sa-tre/satre-specification/issues/59
- https://github.com/sa-tre/satre-specification/issues/60
- https://github.com/sa-tre/satre-specification/issues/61
- https://github.com/sa-tre/satre-specification/issues/62
- https://github.com/sa-tre/satre-specification/issues/63
- https://github.com/sa-tre/satre-specification/issues/64
- https://github.com/sa-tre/satre-specification/issues/65
- https://github.com/sa-tre/satre-specification/issues/66
- https://github.com/sa-tre/satre-specification/issues/67
- https://github.com/sa-tre/satre-specification/issues/68
- https://github.com/sa-tre/satre-specification/issues/69

**Comment by edwardchalstrey1** [comment]
Remaining issues to open @harisood if you want to work from the bottom up if we're dividing labour:

Issue title: Questionnaire summary:7. User experience
####  7.1.a. Windows desktop
| No opinion | Not important | Nice to have | Important | Essential 
| --- | --- | --- | --- | --- 
| 7.62% | 4.76% | 13.33% | 21.90% | 52.38% 
####  7.2.a. Linux desktop
| No opinion | Not important | Nice to have | Important | Essential 
| --- | --- | --- | --- | --- 
| 12.38% | 2.86% | 14.29% | 22.86% | 47.62% 
####  7.3.a. Command line
| No opinion | Not important | Nice to have | Important | Essential 
| --- | --- | --- | --- | --- 
| 14.29% | 2.86% | 20.00% | 18.10% | 44.76% 
####  7.4.a. Non-desktop interfaces e.g. JupyterLab, webapps
| No opinion | Not important | Nice to have | Important | Essential 
| --- | --- | --- | --- | --- 
| 15.24% | 0.95% | 23.81% | 28.57% | 31.43% 

Issue title: Questionnaire summary:8. Programming language support
####  8.1.a. Support for common data science, statistics, ML programming languages (e.g. Python, R)
| No opinion | Not important | Nice to have | Important | Essential 
| --- | --- | --- | --- | --- 
| 2.86% | 0.00% | 1.90% | 15.24% | 80.00% 
Issue title: Questionnaire summary:9. Enable users to install packages from selected external repositories (e.g. PyPI, CRAN, Conda, Maven)
####  9.1.a. Any package
| No opinion | Not important | Nice to have | Important | Essential 
| --- | --- | --- | --- | --- 
| 7.62% | 18.10% | 37.14% | 23.81% | 13.33% 
####  9.2.a. A curated subset of packages
| No opinion | Not important | Nice to have | Important | Essential 
| --- | --- | --- | --- | --- 
| 7.62% | 2.86% | 12.38% | 26.67% | 50.48% 

Issue title: Questionnaire summary:10. Commercially licenced software
####  10.1.a. Ability to use specific commercial software
| No opinion | Not important | Nice to have | Important | Essential 
| --- | --- | --- | --- | --- 
| 9.52% | 3.81% | 21.90% | 34.29% | 30.48% 
####  10.2.a. Further, software that connects to an external licensing server (e.g. SAS)
| No opinion | Not important | Nice to have | Important | Essential 
| --- | --- | --- | --- | --- 
| 17.14% | 9.52% | 28.57% | 30.48% | 14.29% 

Issue title: Questionnaire summary:11. Containerisation
####  11.1.a. Support for running containers (e.g. Docker, Podman, Apptainer)
| No opinion | Not important | Nice to have | Important | Essential 
| --- | --- | --- | --- | --- 
| 23.81% | 2.86% | 19.05% | 30.48% | 23.81% 

Issue title: Questionnaire summary:12. Logging
####  12.1.a. User actions inside the TRE
| No opinion | Not important | Nice to have | Important | Essential 
| --- | --- | --- | --- | --- 
| 2.86% | 2.86% | 14.29% | 29.52% | 50.48% 
####  12.2.a. Network connection attempts
| No opinion | Not important | Nice to have | Important | Essential 
| --- | --- | --- | --- | --- 
| 5.71% | 0.95% | 5.71% | 29.52% | 58.10% 
####  12.3.a. Infrastructure actions (e.g. adding compute, modifying network configuration)
| No opinion | Not important | Nice to have | Important | Essential 
| --- | --- | --- | --- | --- 
| 3.81% | 0.95% | 7.62% | 25.71% | 61.90% 
####  12.4.a. Data access
| No opinion | Not important | Nice to have | Important | Essential 
| --- | --- | --- | --- | --- 
| 1.90% | 0.95% | 6.67% | 23.81% | 66.67% 
####  12.5.a. Real time user and data access logs
| No opinion | Not important | Nice to have | Important | Essential 
| --- | --- | --- | --- | --- 
| 3.81% | 0.95% | 24.76% | 30.48% | 40.00% 
Issue title: Questionnaire summary:13. Automatic updates
####  13.1.a. Software installed on workspaces
| No opinion | Not important | Nice to have | Important | Essential 
| --- | --- | --- | --- | --- 
| 10.48% | 7.62% | 20.00% | 38.10% | 23.81% 
####  13.2.a. User infrastructure (e.g. remote desktop portal, databases, webapps)
| No opinion | Not important | Nice to have | Important | Essential 
| --- | --- | --- | --- | --- 
| 13.33% | 1.90% | 14.29% | 33.33% | 37.14% 
####  13.3.a. Management infrastructure (e.g. logging, configuration management controller)
| No opinion | Not important | Nice to have | Important | Essential 
| --- | --- | --- | --- | --- 
| 13.33% | 0.95% | 10.48% | 33.33% | 41.90% 
####  13.4.a. Anti-virus/malware
| No opinion | Not important | Nice to have | Important | Essential 
| --- | --- | --- | --- | --- 
| 9.52% | 4.76% | 4.76% | 21.90% | 59.05% 

Issue title: Questionnaire summary:14. Compliance checking
####  14.1.a. Vulnerability/security scanning of infrastructure
| No opinion | Not important | Nice to have | Important | Essential 
| --- | --- | --- | --- | --- 
| 7.62% | 0.00% | 1.90% | 20.00% | 70.48% 
####  14.2.a. Machine/resource configuration
| No opinion | Not important | Nice to have | Important | Essential 
| --- | --- | --- | --- | --- 
| 12.38% | 0.00% | 3.81% | 41.90% | 41.90% 
Issue title: Questionnaire summary:15. Automatic backup
####  15.1.a. Input data
| No opinion | Not important | Nice to have | Important | Essential 
| --- | --- | --- | --- | --- 
| 2.86% | 5.71% | 12.38% | 30.48% | 48.57% 
####  15.2.a. User data (e.g. working files)
| No opinion | Not important | Nice to have | Important | Essential 
| --- | --- | --- | --- | --- 
| 0.95% | 1.90% | 8.57% | 29.52% | 59.05% 
####  15.3.a. Workspaces
| No opinion | Not important | Nice to have | Important | Essential 
| --- | --- | --- | --- | --- 
| 3.81% | 2.86% | 15.24% | 31.43% | 46.67% 

Issue title: Questionnaire summary:16. Customisable compute resources
####  16.1.a. Ability to scale compute (CPU, memory)
| No opinion | Not important | Nice to have | Important | Essential 
| --- | --- | --- | --- | --- 
| 12.38% | 0.00% | 10.48% | 31.43% | 45.71% 
####  16.2.a. Accelerators such as GPUs
| No opinion | Not important | Nice to have | Important | Essential 
| --- | --- | --- | --- | --- 
| 14.29% | 0.00% | 18.10% | 35.24% | 32.38% 
Issue title: Questionnaire summary:17. Additional compute beyond workspaces
####  17.1.a. HPC-like resources (i.e. performant hardware, job queue)
| No opinion | Not important | Nice to have | Important | Essential 
| --- | --- | --- | --- | --- 
| 16.19% | 0.00% | 26.67% | 40.00% | 17.14% 
####  17.2.a. Big data and data analytics tools (e.g. Spark, Hadoop)
| No opinion | Not important | Nice to have | Important | Essential 
| --- | --- | --- | --- | --- 
| 17.14% | 0.95% | 37.14% | 29.52% | 15.24% 
####  17.3.a. Integrating with cloud-native managed services (e.g. SageMaker, Athena, Azure ML, Databricks)
| No opinion | Not important | Nice to have | Important | Essential 
| --- | --- | --- | --- | --- 
| 22.86% | 3.81% | 43.81% | 19.05% | 10.48% 

Issue title: Questionnaire summary:18. Collaborative/shared tools
####  18.1.a. Git server (e.g. GitLab/Gitea)
| No opinion | Not important | Nice to have | Important | Essential 
| --- | --- | --- | --- | --- 
| 8.57% | 0.95% | 26.67% | 25.71% | 38.10% 
####  18.2.a. Document writing (e.g. CodiMD)
| No opinion | Not important | Nice to have | Important | Essential 
| --- | --- | --- | --- | --- 
| 26.67% | 1.90% | 42.86% | 23.81% | 4.76% 
####  18.3.a. Databases (e.g. PostgreSQL, MSSQL, MongoDB)
| No opinion | Not important | Nice to have | Important | Essential 
| --- | --- | --- | --- | --- 
| 12.38% | 0.00% | 14.29% | 27.62% | 45.71% 
####  18.4.a. Collaborative coding, visualisation (e.g. Jupyter)
| No opinion | Not important | Nice to have | Important | Essential 
| --- | --- | --- | --- | --- 
| 11.43% | 1.90% | 26.67% | 31.43% | 28.57% 
Issue title: Questionnaire summary:19. Limiting direct access to data/code
####  19.1.a. Users have no direct access to data, submit pipelines or batch jobs, only results are returned
| No opinion | Not important | Nice to have | Important | Essential 
| --- | --- | --- | --- | --- 
| 15.24% | 32.38% | 33.33% | 11.43% | 7.62% 
####  19.2.a. TRE admins don't have access to researcher’s analysis code
| No opinion | Not important | Nice to have | Important | Essential 
| --- | --- | --- | --- | --- 
| 18.10% | 46.67% | 23.81% | 6.67% | 4.76% 
Issue title: Questionnaire summary:20. Reproducible deployments
####  20.1.a. Reproducible TRE deployments (e.g. through infrastructure as code)
| No opinion | Not important | Nice to have | Important | Essential 
| --- | --- | --- | --- | --- 
| 10.48% | 0.00% | 20.00% | 33.33% | 36.19% 

Issue title: Questionnaire summary:23. Sensitivity tiering
####  23.1.a. Support data of different levels of sensitivity
| No opinion | Not important | Nice to have | Important | Essential 
| --- | --- | --- | --- | --- 
| 6.67% | 3.81% | 9.52% | 38.10% | 41.90% 
####  23.2.a. Preset security configurations which can be applied to multiple projects (e.g. a tiered system)
| No opinion | Not important | Nice to have | Important | Essential 
| --- | --- | --- | --- | --- 
| 10.48% | 1.90% | 19.05% | 38.10% | 30.48% 

Issue title: Questionnaire summary:24. Which aspects of governance would it be important or useful to standardise
####  24.1.a. Terms of use
| No opinion | Not important | Nice to have | Important | Essential 
| --- | --- | --- | --- | --- 
| 4.76% | 0.95% | 17.14% | 33.33% | 43.81% 
####  24.2.a. Safe people training users
| No opinion | Not important | Nice to have | Important | Essential 
| --- | --- | --- | --- | --- 
| 5.71% | 0.95% | 10.48% | 39.05% | 43.81% 
####  24.3.a. Safe people training admins
| No opinion | Not important | Nice to have | Important | Essential 
| --- | --- | --- | --- | --- 
| 7.62% | 0.95% | 13.33% | 30.48% | 47.62% 
####  24.4.a. Data ingress and egress processes
| No opinion | Not important | Nice to have | Important | Essential 
| --- | --- | --- | --- | --- 
| 1.90% | 2.86% | 15.24% | 26.67% | 53.33% 
####  24.5.a. Roles and responsibilities
| No opinion | Not important | Nice to have | Important | Essential 
| --- | --- | --- | --- | --- 
| 1.90% | 1.90% | 17.14% | 27.62% | 51.43%
