### ISSUE TITLE
[WIP] Plan for 6th June Collaboration Cafe

### ISSUE THREAD

**Issue by harisood** [sa-tre/satre-team#21]
### Summary of issue

Ensure we have everything in place for the 6th June Collaboration Cafe.

[TO FILL IN IN WP5 MEETING]

### What needs to be done?

- [ ] Prepare the HackMD
- [ ] Prepare the IG breakout room
- [ ] Ensure every work package has some work they are bringing

### Issue checklist

- [X] I have assigned the appropriate work package label to this issue, and added any other relevant labels
- [X] I have added this to the `SATRE backlog (public)` project board
- [X] I have assigned this issue to at least one person on the SATRE team

**Comment by manics** [comment]
If this hasn't been done it's too late!
