### ISSUE TITLE
Submission for RSE Con

### ISSUE THREAD

**Issue by harisood** [sa-tre/satre-team#6]
### Summary of issue

Submitting a proposal for a talk at RSE Con:

- Call for submission: https://rsecon23.society-rse.org/submissions/
- Talk specific guidance: https://rsecon23.society-rse.org/talks/

DUE DATE: Tues 25th April

### What needs to be done?

- [ ] Draft wording for proposal
- [ ] Get feedback from team
- [ ] Submit proposal

### Who can help?

@drchriscole 

Could tag everyone but ultimately Chris needs to be happy with it!

### Issue checklist

- [X] I have assigned the appropriate work package label to this issue, and added any other relevant labels
- [X] I have added this to the `SATRE backlog (public)` project board
- [X] I have assigned this issue to at least one person on the SATRE team

**Comment by harisood** [comment]
[Drafting wording here](https://dmail.sharepoint.com/:w:/r/sites/SATRE/Shared%20Documents/General/4.%20Outputs/RSE_Con/[Talk_proposal.docx](https://dmail.sharepoint.com/:w:/r/sites/SATRE/Shared%20Documents/General/4.%20Outputs/RSE_Con/Talk_proposal.docx?d=w66e9563ba6d7451eafdc93c9718b228a&csf=1&web=1&e=MLJmh9)?d=w66e9563ba6d7451eafdc93c9718b228a&csf=1&web=1&e=MLJmh9)

(only SATRE core team can see)

**Comment by JimMadge** [comment]
Submitted, here is my receipt,

> Dear Jim Madge,
> 
> Thank you for your complete submission titled Standardising UK Trusted Research Environments in the Open. Your reference number for this submission is 63.
> 
> Completed abstracts will be reviewed and you will be informed by Friday, 30th June, 2023 whether or not your submission has been accepted.
